name: Deploy Next.js App to EC2

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          yarn install

      - name: Build Next.js project
        run: |
          yarn build

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private-key.pem
          chmod 400 private-key.pem
           echo "${{ secrets.EC2_PUBLIC_IP }}" 
          ssh -o StrictHostKeyChecking=no -i private-key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /app  
            git pull origin stage  
            yarn install  
            yarn build  
            pm2 restart all 
          EOF
