name: Deploy Next.js App to EC2

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          

      - name: Deploy to EC2
        env:
          SSH_ENDPOINT: ${{ vars.EC2_PUBLIC_IP }}
          SSH_KEY: ${{ vars.EC2_PRIVATE_KEY }}
        run: |
          eval $(ssh-agent -s)
          bash -c 'ssh-add <(echo "$SSH_KEY")'
          ssh -o StrictHostKeyChecking=no -t $SSH_ENDPOINT << EOF
            echo "Deploying application..."
            cd vuonglkdev-gmail.com || exit 1
            git config pull.rebase false # Sử dụng merge để hợp nhất
            git pull origin stage || exit 1
            yarn install --frozen-lockfile || exit 1
            yarn build || exit 1
            pm2 start pm2.config.js || pm2 restart nextjs-app
          EOF
