name: Deploy Next.js App to EC2 using Docker

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nextjs-app:stage .
          docker push ${{ secrets.DOCKER_USERNAME }}/nextjs-app:stage

      - name: Deploy Docker Container on EC2
        env:
          SSH_ENDPOINT: ${{ vars.EC2_PUBLIC_IP }}
          SSH_KEY: ${{ vars.EC2_PRIVATE_KEY }}
        run: |
          eval $(ssh-agent -s)
          bash -c 'ssh-add <(echo "$SSH_KEY")'
          ssh -o StrictHostKeyChecking=no -t $SSH_ENDPOINT << EOF
            echo "Deploying Docker container..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/nextjs-app:stage || exit 1
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker run -d --name nextjs-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/nextjs-app:stage
          EOF
