name: Deploy Next.js App to EC2

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # - name: Install dependencies
      #   run: |
      #     yarn install

      # - name: Build Next.js project
      #   run: |
      #     yarn build

      - name: Deploy to EC2
     env:
          SSH_ENDPOINT: ${{ vars.EC2_PUBLIC_IP }}
          SSH_KEY: ${{ vars.EC2_PRIVATE_KEY }}
        run: |
            eval $(ssh-agent -s)
            bash -c 'ssh-add <(echo "$SSH_KEY")
            bash -c 'ssh-add <(echo "$SSH_KEY")'
            ssh -o StrictHostKeyChecking=no -t $SSH_ENDPOINT 'echo "zolo"'
            cd /vuonglkdev-gmail.com  
            git pull origin stage  
            yarn install  
            yarn build  
            pm2 restart all 

